# Generated by Django 2.1.1 on 2018-09-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180916_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.TaskList'),
        ),
    ]
